// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

#define SRS_AUTO_BUILD_TS "1622227387"
#define SRS_AUTO_BUILD_DATE "2021-05-29 02:43:07"
#define SRS_AUTO_UNAME "Linux banane 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
#define SRS_AUTO_USER_CONFIGURE "--x86-x64  --export-librtmp-project=/home/aarkegz/source/3rd/srs-librtmp-pure --with-ssl"
#define SRS_AUTO_CONFIGURE "--prefix=/usr/local/srs --with-hls --without-hds --with-dvr --without-ssl --without-transcode --without-ingest --without-stat --without-http-callback --with-http-server --without-stream-caster --with-http-api --with-librtmp --with-research --without-utest --without-gperf --without-gmc --without-gmd --without-gmp --without-gcp --without-gprof --log-trace --cc=gcc --cxx=g++ --ar=ar --ld=ld --randlib=randlib"

#define SRS_X86_X64
#define SRS_X86_X64_BOOL true
#define SRS_EXPORT_LIBRTMP

#undef SRS_AUTO_HDS
#define SRS_AUTO_HDS_BOOL false
#undef SRS_AUTO_MEM_WATCH
#define SRS_AUTO_MEM_WATCH_BOOL false
#undef SRS_AUTO_UTEST
#define SRS_AUTO_UTEST_BOOL false
#define SRS_AUTO_FFMPEG_STUB
#define SRS_AUTO_FFMPEG_STUB_BOOL true
#undef SRS_AUTO_GPERF
#define SRS_AUTO_GPERF_BOOL false
#undef SRS_AUTO_GPERF_MC
#define SRS_AUTO_GPERF_MC_BOOL false
#undef SRS_AUTO_GPERF_MD
#define SRS_AUTO_GPERF_MD_BOOL false
#undef SRS_AUTO_GPERF_MP
#define SRS_AUTO_GPERF_MP_BOOL false
#undef SRS_AUTO_GPERF_CP
#define SRS_AUTO_GPERF_CP_BOOL false
#undef SRS_AUTO_VERBOSE
#define SRS_AUTO_VERBOSE_BOOL false
#undef SRS_AUTO_INFO
#define SRS_AUTO_INFO_BOOL false
#define SRS_AUTO_TRACE
#define SRS_AUTO_TRACE_BOOL true
#undef SRS_AUTO_CROSSBUILD
#define SRS_AUTO_CROSSBUILD_BOOL false
#undef SRS_AUTO_OSX
#define SRS_AUTO_OSX_BOOL false

#define SRS_AUTO_PREFIX "/usr/local/srs"

#define SRS_AUTO_CONSTRIBUTORS "\
winlin<winlin@vip.126.com> \
wenjie.zhao<740936897@qq.com> \
xiangcheng.liu<liuxc0116@foxmail.com> \
naijia.liu<youngcow@youngcow.net> \
alcoholyi<alcoholyi@qq.com> \
byteman<wangchen2011@gmail.com> \
chad.wang<chad.wang.cn@gmail.com> \
suhetao<suhetao@gmail.com> \
Johnny<fengjihu@163.com> \
karthikeyan<keyanmca@gmail.com> \
StevenLiu<lq@chinaffmpeg.org> \
zhengfl<zhengfl_1989@126.com> \
tufang14<breadbean1449@gmail.com> \
allspace<allspace@gmail.com> \
niesongsong<nie950@gmail.com> \
rudeb0t<nimrod@themanxgroup.tw> \
CallMeNP<np.liamg@gmail.com> \
synote<synote@qq.com> \
lovecat<littlefawn@163.com> \
panda1986<542638787@qq.com> \
YueHonghui<hongf.yue@hotmail.com> \
ThomasDreibholz<dreibh@simula.no> \
JuntaoLiu<juntliu@gmail.com> \
RocFang<fangpeng1986@gmail.com> \
MakarovYaroslav<yaroslav.makarov.97@mail.ru> \
MirkoVelic<mvelic@inoxx.net> \
HuiZhang(huzhang2)<huzhang2@cisco.com> \
OtterWa<simpleotter23@gmail.com> \
walkermi<172192667@qq.com> \
haofz<fuzhuang.hao@vhall.com> \
ME_Kun_Han<hanvskun@hotmail.com> \
ljx0305<ljx0305@gmail.com> \
cenxinwei<censhanhe@163.com> \
StarBrilliant<m13253@hotmail.com> \
xubin<xubin@chnvideo.com> \
intliang<yintiliang@gmail.com> \
flowerwrong<sysuyangkang@gmail.com> \
YLX<568414379@qq.com> \
J<guotaojiang@qq.com> \
Harlan<hailiang@gvrcraft.com> \
hankun<hankun@bravovcloud.com> \
JonathanBarratt<jonathan.barratt@gmail.com> \
KeeganH<keeganwharris@gmail.com> \
StevenLiu<lingjiujianke@gmail.com> \
liuxc0116<liuxc0116@gmail.com> \
ChengdongZhang<lmajzcd@sina.com> \
lovacat<lovecat@china.sina.com> \
qiang.li<qiang.li@verycdn.com.cn> \
HungMingWu<u9089000@gmail.com> \
Himer<xishizhaohua@qq.com> \
xialixin<xlx0625@163.com> \
alphonsetai<tyh_123@163.com> \
Michael.Ma<wnpllr@gmail.com> \
lam2003<linmin3@yy.com> \
l<22312935+lam2003@users.noreply.github.com> \
xfalcon<x-falcon@users.noreply.github.com> \
"

#endif

